# Generated by Django 4.0.4 on 2022-06-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastname',
        ),
    ]
